
# cargo-vet audits file

[criteria.crypto-safe]
description = """
The cryptographic code in this crate has been reviewed for correctness by a
member of a designated set of cryptography experts within the project.
"""

[criteria.does-not-implement-crypto]
description = """
Does not implement cryptography.
"""

[[audits.base64ct]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = ["safe-to-deploy", "crypto-safe"]
delta = "1.6.0 -> 1.7.3"

[[audits.bitflags]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "2.9.0 -> 2.9.1"

[[audits.cc]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "1.2.22 -> 1.2.24"

[[audits.cpufeatures]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.2.16 -> 0.2.17"

[[audits.data-encoding]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "2.7.0 -> 2.9.0"

[[audits.der]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.7.9 -> 0.7.10"

[[audits.ff]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.13.0 -> 0.13.1"

[[audits.getrandom]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.2.15 -> 0.2.16"

[[audits.getrandom]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = ["safe-to-deploy", "crypto-safe"]
delta = "0.2.15 -> 0.2.16"

[[audits.libloading]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.8.6 -> 0.8.8"

[[audits.p384]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = ["safe-to-deploy", "crypto-safe"]
delta = "0.13.0 -> 0.13.1"

[[audits.ppv-lite86]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.2.20 -> 0.2.21"

[[audits.proc-macro2]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "1.0.94 -> 1.0.95"

[[audits.typenum]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "1.17.0 -> 1.18.0"

[[audits.zerocopy]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.7.35 -> 0.8.25"

[[audits.zerocopy-derive]]
who = "Eric Lagergren <elagergren@spideroak.com>"
criteria = "safe-to-deploy"
delta = "0.7.35 -> 0.8.25"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2026-05-27"

[[trusted.aranya-bearssl-sys]]
criteria = ["safe-to-deploy", "crypto-safe"]
user-id = 293722 # aranya-project-bot
start = "2024-10-15"
end = "2026-01-23"

[[trusted.buggy]]
criteria = ["safe-to-deploy", "does-not-implement-crypto"]
user-id = 293722 # aranya-project-bot
start = "2024-10-16"
end = "2025-12-19"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-05-27"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-05-27"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2026-05-27"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2026-05-27"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-05-27"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2026-05-27"

[[trusted.serde_repr]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-26"
end = "2026-05-27"

[[trusted.sha3-utils]]
criteria = ["safe-to-deploy", "crypto-safe"]
user-id = 3479 # Eric Lagergren (ericlagergren)
start = "2024-12-18"
end = "2026-01-23"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-05-27"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-05-27"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-05-27"

[[trusted.wasi]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2020-06-03"
end = "2026-05-27"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2026-05-27"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-05-27"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2026-05-27"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-05-27"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2026-05-27"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-05-27"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-05-27"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-05-27"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-05-27"
