
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.cargo-vet]
url = "https://raw.githubusercontent.com/mozilla/cargo-vet/refs/heads/main/supply-chain/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.google.criteria-map]
crypto-safe = "crypto-safe"
does-not-implement-crypto = "does-not-implement-crypto"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[imports.zcash.criteria-map]
crypto-safe = "crypto-safe"

[policy.spideroak-crypto]
audit-as-crates-io = false
notes = "SpiderOak crate"

[policy.spideroak-crypto-derive]
audit-as-crates-io = false
notes = "SpiderOak crate"

[[exemptions.aead]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.atomic-polyfill]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bindgen]]
version = "0.70.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.10"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.const-default]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.7.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.ff]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.7.17"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.keccak]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.169"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.15"
criteria = "safe-to-run"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.6.3"
criteria = "safe-to-deploy"

[[exemptions.merlin]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.more-asserts]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.p384]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.2.29"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.34"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.25"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.137"
criteria = "safe-to-deploy"

[[exemptions.serde_repr]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.96"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.96"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.15.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "2.0.11"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.11"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wycheproof]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"
