[package]
name = "canary-alloc"
publish = false
authors.workspace = true
edition.workspace = true
license = "BSD-3-Clause"
rust-version.workspace = true

[dependencies]
# spideroak-crypto` enables `getrandom` by default.
spideroak-crypto = { path = "../../crates/crypto", default-features = false }
