/*
 * Copyright (c) SpiderOak, Inc. All rights reserved.
 */
/**
 * @file spideroak-crypto.h
 * @brief External header file containing C function definitions
 * for the Aranya client library.
 */
 

#ifndef SPIDEROAK_CRYPTO_H
#define SPIDEROAK_CRYPTO_H

#pragma once

/* Code generated by `capi`. DO NOT EDIT. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef __has_attribute
    #define __has_attribute(x) 0
#endif /* __has_attribute */

#if !defined(SPIDEROAK_CRYPTO_ALIGNED)
    #if __has_attribute(aligned)
        #define SPIDEROAK_CRYPTO_ALIGNED(n) __attribute__((aligned(n)))
    #else
        #error "compiler must support `aligned` attribute"
    #endif
#endif /* SPIDEROAK_CRYPTO_ALIGNED */

#if !defined(SPIDEROAK_CRYPTO_DESIGNATED_INIT)
    #if __has_attribute(designated_init)
        #define SPIDEROAK_CRYPTO_DESIGNATED_INIT __attribute__((designated_init))
    #else
        #define SPIDEROAK_CRYPTO_DESIGNATED_INIT
    #endif
#endif /* SPIDEROAK_CRYPTO_DESIGNATED_INIT */

#if !defined(SPIDEROAK_CRYPTO_MUST_USE)
    #if __has_attribute(warn_unused_result)
        #define SPIDEROAK_CRYPTO_MUST_USE __attribute__((warn_unused_result))
    #else
        #define SPIDEROAK_CRYPTO_MUST_USE
    #endif
#endif /* SPIDEROAK_CRYPTO_MUST_USE */

#if !defined(SPIDEROAK_CRYPTO_NO_RETURN)
    #if __has_attribute(noreturn)
        #define SPIDEROAK_CRYPTO_NO_RETURN __attribute__((noreturn))
    #else
        #define SPIDEROAK_CRYPTO_NO_RETURN
    #endif
#endif /* SPIDEROAK_CRYPTO_NO_RETURN */

#if !defined(SPIDEROAK_CRYPTO_NON_NULL)
    #if defined(__gnu__)
        #if __has_attribute(nonnull)
            #define SPIDEROAK_CRYPTO_NON_NULL __attribute__((nonnull))
        #endif
    #elif defined(__clang__)
        #define SPIDEROAK_CRYPTO_NON_NULL _Nonnull
    #else
        #define SPIDEROAK_CRYPTO_NON_NULL
    #endif
#endif /* SPIDEROAK_CRYPTO_NON_NULL */

#if !defined(SPIDEROAK_CRYPTO_PACKED)
    #if __has_attribute(packed)
        #define SPIDEROAK_CRYPTO_PACKED __attribute__((packed))
    #else
        #define SPIDEROAK_CRYPTO_PACKED
    #endif
#endif /* SPIDEROAK_CRYPTO_PACKED */

/**
 * Unused.
 */
typedef struct ENGINE ENGINE;


#endif  /* SPIDEROAK_CRYPTO_H */


